// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFilesByFolderID(arg1) {
  return window['go']['main']['App']['DeleteFilesByFolderID'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function GetAllFolders() {
  return window['go']['main']['App']['GetAllFolders']();
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function GetFolder(arg1) {
  return window['go']['main']['App']['GetFolder'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateFile'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateFileContent(arg1, arg2) {
  return window['go']['main']['App']['UpdateFileContent'](arg1, arg2);
}

export function UpdateFileName(arg1, arg2) {
  return window['go']['main']['App']['UpdateFileName'](arg1, arg2);
}
