// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function GetAllFolders() {
  return window['go']['main']['App']['GetAllFolders']();
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateFile'](arg1, arg2, arg3, arg4, arg5);
}
